[package]
name = "opaliha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
ndarray = "0.15.6"
regex = "1.8.1"
yaml-rust = "0.4.5"

[profile.release]
panic = 'abort'
